### ISSUE TITLE
Array value of meta[peers]

### ISSUE THREAD

**Issue by xiii** [olivierHa/puppet-influxdb#10]
Hello,

I am clustering influx and I need the meta[peers] but because this value is an array the template needs to be changed to use value.is_a?(Array) too(like the graphite section). Do you want me to PR it or is something you can push ?

Thanks,
Efstathios

**Comment by olivierHa** [comment]
I will push it in a few min.
Thanks

**Comment by xiii** [comment]
Thanks Olivier!

**Comment by olivierHa** [comment]
You're welcome. It's pushed.
If you got an example of clustering, could you update the Readme ?
I think it could help other people using this module.

**Comment by xiii** [comment]
I will :)

**Comment by xiii** [comment]
You said you pushed but I don't see it

**Comment by olivierHa** [comment]
my bad !
I've pushed without commit :)
It's done
