### ISSUE TITLE
Manage continuous queries and users

### ISSUE THREAD

**Issue by dhoppe** [olivierHa/puppet-influxdb#11]
Hello Olivier, 

I love the idea of managing databases and retention policies via Puppet providers and it would be great to have an additional provider for continuous queries and users. 

Kind regards, 
Dennis

**Comment by olivierHa** [comment]
Hello Dennis,

Yes additional provider will be added on next releases, it is on the roadmap. 
PR are accepted ;)

I am also waiting that influxdb team provides a config file to read user/password from it (like mysql)

Regards

Olivier
