### ISSUE TITLE
Cannot use custom providers when authentication is enabled

### ISSUE THREAD

**Issue by madAndroid** [olivierHa/puppet-influxdb#17]
In order to use Grafana 2.5 with InfluxDB, we have to enable authentication .. and then discovered this module's custom types and providers don't work when authentication is enabled.

I'm putting together a pull-request that will address this, as well as creating users.

**Comment by olivierHa** [comment]
Hello
I think you can use grafana with influxdb without authentification.
But yes, this module doesnt handle yet authentification.
I was hoping that influxdb will support à .influxdb.conf file in which we
can specify some creds.
Olivier

**Comment by madAndroid** [comment]
Hey :)

With the version of Grafana we're using (currently 2.5) - we're not able to specify no auth for Influx datasource:

![grafana_-_auth](https://cloud.githubusercontent.com/assets/1321437/15207261/3389e5a6-1825-11e6-8f4b-fa432757442d.jpg)

Not sure if this is fixed in a newer version though. Interestingly, we can disable auth once the config is set, and Grafana continues to function, so it's probably not a hard requirement, in spite of Grafana not allowing us to skip authentication when adding the datasource via the console. The `bfraser/grafana` puppet module does allow us to create the datasource though, so I'm not quite sure what's going on :-/

**Comment by madAndroid** [comment]
Until Influx themselves revisit the authentication mechanism (see https://github.com/influxdata/influxdb/issues/4904 and https://github.com/influxdata/influxdb/issues/2278 for examples) it's probably not worth adding this capability.
