### ISSUE TITLE
Graphite template config should be split over multiple lines

### ISSUE THREAD

**Issue by madAndroid** [olivierHa/puppet-influxdb#18]
As per the docs here: https://github.com/influxdata/influxdb/blob/master/services/graphite/README.md
For readability, an array in the INI should be written on multiple lines; currently an array of templates is written on a single line; when there are multiple template and they've each got a long string, this can become difficult to read in the config.

Are you open to the idea of changing the template to write arrays onto multiple lines?
This would result in config with:

```
   templates = [
     "*.app env.service.resource.measurement",
     "stats.* .host.measurement* region=us-west,agent=sensu",
     "stats.* .host.measurement.field",
     ".measurement*",
   ]
```

instead of:

```
   templates = [ "*.app env.service.resource.measurement", "stats.* .host.measurement* region=us-west,agent=sensu", "stats.* .host.measurement.field", ".measurement*"  ]
```

**Comment by AshtonDavis** [comment]
Much better.  Thanks for cleaning it up.

**Comment by olivierHa** [comment]
PR has been merged ! Thanks to both for you !
