### ISSUE TITLE
custom provider not working on latest influxdb 0.9.6 rpm

### ISSUE THREAD

**Issue by wbean1** [olivierHa/puppet-influxdb#4]
with a definition like:

```
  influxdb_database { 'collectd':
    ensure  => 'present',
  }

  influxdb_retention_policy { '2w@collectd':
    ensure      => 'present',
    database    => 'collectd',
    duration    => '2w',
    is_default  => true,
    replication => '1',
  }
```

I get:

```
Error: Could not find a suitable provider for influxdb_retention_policy
Error: Could not find a suitable provider for influxdb_database
```

more detail:

```
[root@influxdb2 ~]# puppet resource influxdb_retention_policy --debug
Debug: Runtime environment: puppet_version=3.8.4, ruby_version=2.0.0, run_mode=user, default_encoding=UTF-8
Debug: Puppet::Type::Influxdb_retention_policy::ProviderRuby: file /opt/influxdb/influx does not exist
Debug: Puppet::Type::Influxdb_retention_policy::ProviderRuby: file /opt/influxdb/influx does not exist

[root@influxdb2 ~]# which influx
/bin/influx
```

I'm guessing they adjusted the rpm packaging (I'm using EL7) to change the binary install location.  If the issue wasn't hardcoded in a custom provider, I'd offer a PR... but i don't know my way around those very well...

https://github.com/olivierHa/puppet-influxdb/blame/7e95c5c24dc2f209117509e8602ba80453afefd8/lib/puppet/provider/influxdb_database/ruby.rb#L4 

Looks like packaging was changed in 0.9.5: https://github.com/influxdb/influxdb/blob/master/CHANGELOG.md#v095-2015-11-20

**Comment by olivierHa** [comment]
Hello,

Indeed, I need to rewrite some parts of this module to be compatible with influxdb 0.9.5 and later.
I got some other stuffs to include, so you can expect a new release soon :)

Regards

Olivier

**Comment by olivierHa** [comment]
Hello, 

The rewriting of this module is almost finished. I've updated the binary location.
Could you give a try ?

Regards

Olivier

**Comment by wbean1** [comment]
Now having a new issue that prevents influxdb service from starting:

```
2016/02/03 15:04:37 Using configuration at: /etc/influxdb/influxdb.conf
run: parse config: Type mismatch for 'run.Config.data': Type mismatch for 'tsdb.Config.wal-compaction-threshold': Expected float but found 'string'.
```

the value is being quoted where I guess its supposed to not be...

```
wal-compaction-threshold = "0.5"
```

I'm guessing this may be due to my version of puppet (3.8.4) not being strictly-typed like 4.0 is?  So the default for this (which looks correct in params.pp) gets shoved into a string, then the template wraps it in quotes...

**Comment by olivierHa** [comment]
I've merged your PR.
I will add an acceptance test for this. 
Thanks !
