### ISSUE TITLE
Comment on releases & version

### ISSUE THREAD

**Issue by xiii** [olivierHa/puppet-influxdb#8]
Hey, not really a serious issue but will be good if you could keep releases or tags reflecting your versions. Also that latest release with the module refactor was kinda a breaking one :) so would be nice to reflect that with a major release update.

thanks for the module though! I like the refactor too.
Cheers

PS forge version update too!

**Comment by olivierHa** [comment]
In fact, when I started this module, I thought i will give the 1.0 version, when influxdb will release their 1.0 version.

I didn't upload this module yet into the forge. Do you think it is worth to update this module  to a 1.0 version ?

**Comment by xiii** [comment]
Ah I see, good point! I think as long your CHANGELOG matches a github release or a tag is fine for people tracking the progress. Then if rspec/acceptance tests pass you can update the forge release too. 

I suppose that last refactor put the module in the right track and we can expect less breaking changes in the future.

I can help you with the releases btw if you don't have time.

**Comment by olivierHa** [comment]
Indeed, the core of this module will remain this way, unless influxdb team breaks everything, like switching to a xml config file :D
